version: '3'

services:
  jbrowse:
    build: docker/jbrowse
    image: togovar_jbrowse:${VERSION:-latest}
    volumes:
      - ./docker/jbrowse/template/jbrowse_conf.json:/var/www/jbrowse_conf.json:ro
      - ${JBROWSE_VOLUMES_DATA:-./data/jbrowse/data}:/var/www/data
    ports:
      - "${JBROWSE_PORT:-8080}:8080"

  sparqlist:
    image: ghcr.io/dbcls/sparqlist:snapshot-fffa8c9
    environment:
      ADMIN_PASSWORD: ${SPARQLIST_ADMIN_PASSWORD:-changeme}
      SPARQLIST_TOGOVAR_SPARQL: http://sparql-proxy:3000/sparql
      SPARQLIST_TOGOVAR_SEARCH: http://nginx/search
      SPARQLIST_TOGOVAR_SPARQLIST: http://sparqlist:3000/sparqlist
    volumes:
      - ./sparqlist:/app/repository
    ports:
      - "${SPARQLIST_PORT:-8081}:3000"

  sparql-proxy:
    image: ghcr.io/dbcls/sparql-proxy:snapshot-e2af119
    environment:
      SPARQL_BACKEND: http://virtuoso:8890/sparql
      ADMIN_USER: admin
      ADMIN_PASSWORD: ${SPARQL_PROXY_ADMIN_PASSWORD:-changeme}
      CACHE_STORE: redis
      REDIS_URL: redis://redis:6379
      MAX_CONCURRENCY: 50
    depends_on:
      - virtuoso
      - redis
    ports:
      - "${SPARQL_PROXY_PORT:-8082}:3000"

  virtuoso:
    build: docker/virtuoso
    image: togovar_virtuoso:${VERSION:-latest}
    environment:
      DBA_PASSWORD: dba
      SPARQL_UPDATE: "false"
      DEFAULT_GRAPH: http://togovar.biosciencedbc.jp
      VIRT_Parameters_DirsAllowed: /load
      VIRT_SPARQL_MaxQueryCostEstimationTime: 6000
      VIRT_SPARQL_MaxQueryExecutionTime: 600
      VIRT_SPARQL_ResultSetMaxRows: 1000000
      VIRT_URIQA_DefaultHost: togovar.biosciencedbc.jp
      ## Uncomment next two lines if there is 2 GB system memory free
      #VIRT_Parameters_NumberOfBuffers: 170000
      #VIRT_Parameters_MaxDirtyBuffers: 130000
      ## Uncomment next two lines if there is 4 GB system memory free
      #VIRT_Parameters_NumberOfBuffers: 340000
      #VIRT_Parameters_MaxDirtyBuffers: 250000
      ## Uncomment next two lines if there is 8 GB system memory free
      #VIRT_Parameters_NumberOfBuffers: 680000
      #VIRT_Parameters_MaxDirtyBuffers: 500000
      ## Uncomment next two lines if there is 16 GB system memory free
      #VIRT_Parameters_NumberOfBuffers: 1360000
      #VIRT_Parameters_MaxDirtyBuffers: 1000000
      ## Uncomment next two lines if there is 32 GB system memory free
      #VIRT_Parameters_NumberOfBuffers: 2720000
      #VIRT_Parameters_MaxDirtyBuffers: 2000000
      ## Uncomment next two lines if there is 48 GB system memory free
      #VIRT_Parameters_NumberOfBuffers: 4000000
      #VIRT_Parameters_MaxDirtyBuffers: 3000000
      ## Uncomment next two lines if there is 64 GB system memory free
      VIRT_Parameters_NumberOfBuffers: 5450000
      VIRT_Parameters_MaxDirtyBuffers: 4000000
    volumes:
      - ./docker/virtuoso/bin/rdf:/usr/local/bin/rdf:ro
      - ./docker/virtuoso/config:/config:ro
      - ${VIRTUOSO_VOLUMES_LOAD:-./data/virtuoso/load}:/load
      - ${VIRTUOSO_VOLUMES_DATABASE:-./data/virtuoso/database}:/database
      - ${VIRTUOSO_VOLUMES_SETTINGS:-./data/virtuoso/settings}:/settings
    ports:
      - "${VIRTUOSO_PORT:-8890}:8890"

  redis:
    image: redis:6

  elasticsearch01: &es
    image: elasticsearch:7.16.3
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment: &es_env
      discovery.seed_hosts: elasticsearch02,elasticsearch03,elasticsearch04,elasticsearch05
      node.name: node01
      cluster.initial_master_nodes: node01,node02,node03,node04,node05
      ES_JAVA_OPTS: -Xms16g -Xmx16g
      bootstrap.memory_lock: "true"
      xpack.monitoring.collection.enabled: "true"
      xpack.security.enabled: "false"
      path.repo: /usr/share/elasticsearch/snapshot
    depends_on:
      - elasticsearch02
      - elasticsearch03
      - elasticsearch04
      - elasticsearch05
    volumes:
      - ${ELASTICSEARCH_VOLUMES_01_DATA:-./data/elasticsearch/01}:/usr/share/elasticsearch/data
      - ${ELASTICSEARCH_VOLUMES_SNAPSHOT:-./data/elasticsearch/snapshot}:/usr/share/elasticsearch/snapshot
    ports:
      - "${ELASTICSEARCH_PORT:-9200}:9200"

  elasticsearch02:
    <<: *es
    environment:
      <<: *es_env
      node.name: node02
      discovery.seed_hosts: elasticsearch01,elasticsearch03,elasticsearch04,elasticsearch05
      cluster.initial_master_nodes: node01,node02,node03,node04,node05
    volumes:
      - ${ELASTICSEARCH_VOLUMES_02_DATA:-./data/elasticsearch/02}:/usr/share/elasticsearch/data
      - ${ELASTICSEARCH_VOLUMES_SNAPSHOT:-./data/elasticsearch/snapshot}:/usr/share/elasticsearch/snapshot
    depends_on: []
    ports: []

  elasticsearch03:
    <<: *es
    environment:
      <<: *es_env
      node.name: node03
      discovery.seed_hosts: elasticsearch01,elasticsearch02,elasticsearch04,elasticsearch05
      cluster.initial_master_nodes: node01,node02,node03,node04,node05
    volumes:
      - ${ELASTICSEARCH_VOLUMES_03_DATA:-./data/elasticsearch/03}:/usr/share/elasticsearch/data
      - ${ELASTICSEARCH_VOLUMES_SNAPSHOT:-./data/elasticsearch/snapshot}:/usr/share/elasticsearch/snapshot
    depends_on: []
    ports: []

  elasticsearch04:
    <<: *es
    environment:
      <<: *es_env
      node.name: node04
      discovery.seed_hosts: elasticsearch01,elasticsearch02,elasticsearch03,elasticsearch05
      cluster.initial_master_nodes: node01,node02,node03,node04,node05
    volumes:
      - ${ELASTICSEARCH_VOLUMES_04_DATA:-./data/elasticsearch/04}:/usr/share/elasticsearch/data
      - ${ELASTICSEARCH_VOLUMES_SNAPSHOT:-./data/elasticsearch/snapshot}:/usr/share/elasticsearch/snapshot
    depends_on: []
    ports: []

  elasticsearch05:
    <<: *es
    environment:
      <<: *es_env
      node.name: node05
      discovery.seed_hosts: elasticsearch01,elasticsearch02,elasticsearch03,elasticsearch04
      cluster.initial_master_nodes: node01,node02,node03,node04,node05
    volumes:
      - ${ELASTICSEARCH_VOLUMES_05_DATA:-./data/elasticsearch/05}:/usr/share/elasticsearch/data
      - ${ELASTICSEARCH_VOLUMES_SNAPSHOT:-./data/elasticsearch/snapshot}:/usr/share/elasticsearch/snapshot
    depends_on: []
    ports: []

  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.3
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch01:9200
      I18N_LOCALE: ja-JP
    depends_on:
      - elasticsearch01
    ports:
      - "${KIBANA_PORT:-5601}:5601"
